
theme = "sys"

[editor]
shell = ["fish"]


[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "position", "file-encoding", "file-type"]
separator = "|"


# Make this language-specific?
[editor.indent-guides]
render = true