
autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif 



call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-commentary'
Plug 'plasticboy/vim-markdown'
call plug#end()


let g:tex_flavor = "latex"
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_auto_insert_bullets = 0



" Split movement
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set guicursor=a:hor100
set guicursor+=a:blinkon0

set tabstop=4
set shiftwidth=4
set autoindent
set showcmd
set swapfile


" Appearance
syntax on
colorscheme default
set t_Co=16             " 16 colours (xresources)
highlight ColorColumn ctermbg=0

" File specific stuff 
filetype plugin on
filetype indent on
set ffs=unix            " Unix files
set autoread            " reload if written elsewhere 
set showmatch           " match brackets

" No bells
set noerrorbells
set novisualbell

set mouse=v



" Fork Make
function! MAKE()
        let result = system("make > /dev/null &")
endfunction

command M call MAKE()




autocmd BufRead,BufNewFile *TODO set ft=markdown
