

set guicursor=a:hor100


set tabstop=4
set shiftwidth=4
set autoindent
set showcmd

" Appearance
syntax on
colorscheme default
set t_Co=16             " 16 colours (xresources)


" File specific stuff 
filetype plugin on
filetype indent on
set ffs=unix            " Unix files
set autoread            " reload if written elsewhere 
set showmatch           " match brackets

" No bells
set noerrorbells
set novisualbell

set mouse=v



" Fork Make
function! MAKE()
        let result = system("make > /dev/null &")
endfunction
command M call MAKE()



